apiVersion: apps/v1
kind: Deployment
metadata:
  name: eka-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eka-api
  template:
    metadata:
      labels:
        app: eka-api
    spec:
      containers:
        - name: fastapi-app
          image: raushan0291/eka-base:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: REDIS_SERVER_HOST
              value: "redis"
            - name: REDIS_SERVER_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: CACHE_TTL
              value: "3600"
            # - name: POSTGRES_URL
            #   value: "postgresql://postgres:postgres@postgres:5432/eka"
            - name: CHROMA_SERVER_HOST
              value: "chroma"
            - name: CHROMA_SERVER_PORT
              value: "8000"
            - name: MODEL_NAME
              value: "google/flan-t5-base"
          command: ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8001"]
