apiVersion: v1
kind: Service
metadata:
  name: eka-api
spec:
  selector:
    app: eka-api
  ports:
    - port: 8001  # Port exposed by the service
      targetPort: 8001 # Port on which the container is listening
  type: ClusterIP
